parameters:
    htime.light_cms_bundle.snippet_manager.class: Htime\LightCmsBundle\Manager\SnippetManager

services:
    htime.light_cms_bundle.snippet_manager:
        class: %htime.light_cms_bundle.snippet_manager.class%
        arguments: [@doctrine.orm.entity_manager, @twig]
        tags:
            - { name: twig.extension }